# Generated by Django 5.2 on 2025-04-23 07:11

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "variant",
            },
        ),
        migrations.AddField(
            model_name="productmodel",
            name="avg_rating",
            field=models.FloatField(blank=True, db_column="avg_rating", null=True),
        ),
        migrations.CreateModel(
            name="ProductItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sku", models.CharField(max_length=255)),
                ("stock", models.IntegerField()),
                ("price", models.FloatField()),
                (
                    "image_urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1000),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "productId",
                    models.ForeignKey(
                        db_column="productId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="base.productmodel",
                    ),
                ),
            ],
            options={
                "db_table": "productItem",
            },
        ),
        migrations.CreateModel(
            name="ProductConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "productId",
                    models.ForeignKey(
                        db_column="productId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.productmodel",
                    ),
                ),
                (
                    "variantId",
                    models.ForeignKey(
                        db_column="variantId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.variant",
                    ),
                ),
            ],
            options={
                "db_table": "productConfig",
                "unique_together": {("productId", "variantId")},
            },
        ),
        migrations.CreateModel(
            name="VariationType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "categoryID",
                    models.ForeignKey(
                        blank=True,
                        db_column="categoryID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.categorymodel",
                    ),
                ),
            ],
            options={
                "db_table": "variationType",
            },
        ),
        migrations.AddField(
            model_name="variant",
            name="variationTypeId",
            field=models.ForeignKey(
                db_column="variationTypeId",
                on_delete=django.db.models.deletion.CASCADE,
                to="base.variationtype",
            ),
        ),
        migrations.DeleteModel(
            name="ProductSizeModel",
        ),
    ]
