# Generated by Django 5.2.1 on 2025-05-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='refreshToken',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
