# Generated by Django 5.2 on 2025-05-02 05:22

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="level",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="lft",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="rght",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="parentCategory",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                db_column="parentCategory",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="base.categorymodel",
            ),
        ),
    ]
