# Generated by Django 5.2 on 2025-04-13 01:14

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('NAME', models.CharField(max_length=255)),
                ('DESCRIPTION', models.CharField(max_length=255)),
                ('IMAGES', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, size=None)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
