# Generated by Django 5.2 on 2025-04-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_productmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='DESCRIPTION',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='IMAGES',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='NAME',
            new_name='name',
        ),
    ]
