# Generated by Django 5.2 on 2025-05-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_addressbookmodel_alter_usermodel_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddressmodel',
            old_name='is_default',
            new_name='isDefault',
        ),
    ]
