# Generated by Django 5.2 on 2025-04-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_description_productmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
