# Generated by Django 5.2.3 on 2025-06-13 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_add_search_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('productItem', models.ForeignKey(db_column='productItemId', on_delete=django.db.models.deletion.CASCADE, to='base.productitemmodel')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shoppingCartItem',
                'unique_together': {('productItem', 'user')},
            },
        ),
    ]
