# Generated by Django 5.2.3 on 2025-06-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_add_search_indexes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddressBookModel',
            new_name='AddressModel',
        ),
        migrations.AlterModelTable(
            name='addressmodel',
            table='address',
        ),
    ]
