# Generated by Django 5.2 on 2025-04-16 09:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_productmodel_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('parentCategoryId', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
