# Generated by Django 5.2.3 on 2025-08-05 10:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_addressbookmodel_addressmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('productItem', models.ForeignKey(db_column='productItemId', on_delete=django.db.models.deletion.CASCADE, to='base.productitemmodel')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shoppingCartItem',
                'unique_together': {('productItem', 'user')},
            },
        ),
    ]
