# Generated by Django 5.2.5 on 2025-08-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_shoppingcartitemmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationModel",
            fields=[
                (
                    "country_code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("country_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "location",
            },
        ),
        migrations.AddField(
            model_name="productmodel",
            name="locations",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="base.locationmodel"
            ),
        ),
    ]
