# Generated by Django 5.2 on 2025-04-17 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.categorymodel')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.productmodel')),
            ],
            options={
                'db_table': 'productCategory',
            },
        ),
        migrations.CreateModel(
            name='ProductSizeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('size', models.CharField(max_length=7)),
                ('price', models.FloatField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.productmodel')),
            ],
            options={
                'db_table': 'productSize',
            },
        ),
    ]
