# Generated by Django 5.2.3 on 2025-08-17 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_shoppingcartitemmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingVendorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('logoUrl', models.TextField()),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'shippingVendor',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('totalPrice', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('address', models.ForeignKey(db_column='addressId', on_delete=django.db.models.deletion.CASCADE, to='base.addressmodel')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shippingVendor', models.ForeignKey(db_column='shippingVendorId', on_delete=django.db.models.deletion.CASCADE, to='base.shippingvendormodel')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('productItem', models.ForeignKey(db_column='productItemId', on_delete=django.db.models.deletion.CASCADE, to='base.productitemmodel')),
                ('order', models.ForeignKey(db_column='orderId', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base.ordermodel')),
            ],
            options={
                'db_table': 'orderItem',
            },
        ),
    ]
