# Generated by Django 5.2.5 on 2025-08-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_locationmodel_productmodel_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmodel',
            name='currency_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='locationmodel',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='CurrencyRateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3, unique=True)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'currency_rate',
                'indexes': [models.Index(fields=['currency_code'], name='currency_ra_currenc_916fbc_idx'), models.Index(fields=['last_updated'], name='currency_ra_last_up_6e7fde_idx')],
            },
        ),
    ]
