# Generated by Django 5.2 on 2025-04-17 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_productcategorymodel_productsizemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodel',
            name='categoryId',
            field=models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.CASCADE, to='base.categorymodel'),
        ),
        migrations.AlterField(
            model_name='productcategorymodel',
            name='productId',
            field=models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='base.productmodel'),
        ),
        migrations.AlterField(
            model_name='productsizemodel',
            name='productId',
            field=models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='base.productmodel'),
        ),
    ]
