# Generated by Django 5.2.1 on 2025-09-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_guestusermodel_shippingvendormodel_ordermodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='paymentIntentId',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
