# Generated by Django 5.2.6 on 2025-09-30 03:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_add_payment_intent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='shippingVendor',
        ),
        migrations.CreateModel(
            name='ShipmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('trackingNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('in_transit', 'In_Transit'), ('out_for_delivery', 'Out_For_Delivery'), ('delivered', 'Delivered'), ('failed_delivery', 'Failed_Delivery'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('earliestDeliveryDate', models.DateField(blank=True, null=True)),
                ('latestDeliveryDate', models.DateField(blank=True, null=True)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(db_column='orderId', on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='base.ordermodel')),
                ('shippingVendor', models.ForeignKey(db_column='shippingVendorId', on_delete=django.db.models.deletion.CASCADE, to='base.shippingvendormodel')),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='shipment',
            field=models.ForeignKey(blank=True, db_column='shipmentId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='base.shipmentmodel'),
        ),
    ]
