# Generated by Django 5.2 on 2025-04-19 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_productmodel_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productsizemodel",
            name="price",
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="gender",
            field=models.CharField(default="Unisex", max_length=10),
        ),
        migrations.CreateModel(
            name="ProductColourModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("colour", models.CharField(max_length=50)),
                (
                    "productId",
                    models.ForeignKey(
                        db_column="productId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.productmodel",
                    ),
                ),
            ],
            options={
                "db_table": "productColour",
            },
        ),
        migrations.CreateModel(
            name="ProductPriceModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "productId",
                    models.OneToOneField(
                        db_column="productId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price",
                        to="base.productmodel",
                    ),
                ),
            ],
            options={
                "db_table": "productPrice",
            },
        ),
    ]
