# Generated by Django 5.2.3 on 2025-10-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_ordermodel_shippingvendor_shipmentmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller'), ('manager', 'Manager'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
    ]
