# Generated by Django 5.2.3 on 2025-10-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_usermodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
