# Generated by Django 5.2.5 on 2025-10-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_ordermodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
