# Generated by Django 5.2.3 on 2025-10-04 03:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_ordermodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitemmodel',
            name='imageUrls',
        ),
        migrations.RemoveField(
            model_name='productitemmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='name',
        ),
        migrations.CreateModel(
            name='ProductItemLocationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount', models.FloatField(validators=[django.core.validators.MaxValueValidator(100.0)])),
                ('startDate', models.DateTimeField(blank=True, db_column='startDate', null=True)),
                ('endDate', models.DateTimeField(blank=True, db_column='endDate', null=True)),
                ('location', models.ForeignKey(db_column='locationId', on_delete=django.db.models.deletion.CASCADE, related_name='productItems', to='base.locationmodel')),
                ('productItem', models.ForeignKey(db_column='productItemId', on_delete=django.db.models.deletion.CASCADE, related_name='locationPrices', to='base.productitemmodel')),
            ],
            options={
                'db_table': 'productItemLocation',
                'constraints': [models.CheckConstraint(condition=models.Q(('discount__lte', 100.0)), name='discount_max_100')],
                'unique_together': {('productItem', 'location')},
            },
        ),
        migrations.CreateModel(
            name='ProductLocationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('location', models.ForeignKey(db_column='locationId', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='base.locationmodel')),
                ('product', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='base.productmodel')),
            ],
            options={
                'db_table': 'productLocation',
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0.0)), name='price_min_0')],
                'unique_together': {('product', 'location')},
            },
        ),
    ]
