# Generated by Django 5.2.5 on 2025-10-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_productitemmodel_imageurls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmodel',
            name='currency_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
