# Generated by Django 5.2.5 on 2025-10-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_locationmodel_currency_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationtypemodel',
            name='category',
        ),
        migrations.AddField(
            model_name='variationtypemodel',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='variation_types', to='base.categorymodel'),
        ),
    ]
