# Generated by Django 5.2.3 on 2025-10-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_locationmodel_currency_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='mfa_enabled',
            field=models.BooleanField(db_column='mfaEnabled', default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='mfa_secret',
            field=models.CharField(blank=True, db_column='mfaSecret', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_active',
            field=models.BooleanField(db_column='isActive', default=True),
        ),
    ]
