# Generated by Django 5.2.3 on 2025-10-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_usermodel_is_staff_usermodel_mfa_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variationtypemodel',
            name='category',
        ),
        migrations.AddField(
            model_name='variationtypemodel',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='variation_types', to='base.categorymodel'),
        ),
    ]
