# Generated by Django 5.2.5 on 2025-10-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_usermodel_is_staff_usermodel_mfa_enabled_and_more'),
        ('base', '0014_remove_variationtypemodel_category_and_more'),
    ]

    operations = [
    ]
